name: cepi
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - astroid=2.6.6=py39hf3d152e_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - autopep8=1.5.7=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.2.1=py39hdb19cb5_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.13=py39hf88036b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - expat=2.7.0=h5888daf_0
  - flake8=3.9.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.55.3=py39h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - h5py=3.12.1=py39h5842655_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - icu=73.2=h59595ed_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - isort=5.13.2=pyhd8ed1ab_1
  - joblib=1.4.2=py39h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.10.0=py39h8cd3c5a_2
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libcap=2.71=h39aace5_0
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=17.0.6=default_h97e9c88_4
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.80.2=hf974151_0
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - libllvm14=14.0.6=hecde1de_4
  - libllvm15=15.0.7=he89c38a_4
  - libllvm17=17.0.6=h0ad199c_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.43=h2797004_0
  - libpq=16.8=h87c4ccc_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=256.9=h2774228_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.43.0=py39h6a678d5_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.9.2=py39h06a4308_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.6.1=py_1
  - mpg123=1.32.9=hc50e24c_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nspr=4.35=h6a678d5_0
  - nss=3.100=hca3bf56_0
  - numba=0.60.0=py39h0320e7d_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.5.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - ply=3.11=py39h06a4308_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycodestyle=2.7.0=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=2.3.1=pyhd8ed1ab_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pylint=2.9.6=pyhd8ed1ab_0
  - pynndescent=0.5.4=pyhd3eb1b0_0
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_1
  - pyqt5-sip=12.13.0=py39h5eee18b_1
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.2.4=pyhd8ed1ab_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=26.2.1=py39h4e4fb57_0
  - qt-main=5.15.8=hc9dc06e_21
  - readline=8.2=h5eee18b_0
  - rope=1.13.0=pyhd8ed1ab_1
  - scikit-learn=1.6.1=py39h6a678d5_0
  - scipy=1.13.1=py39heeff2f4_1
  - seaborn=0.13.2=py39h06a4308_3
  - setuptools=75.8.0=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_1
  - six=1.17.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py39h8cd3c5a_0
  - tqdm=4.67.1=py39h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - ujson=5.10.0=py39hf88036b_1
  - umap-learn=0.5.9.post2=py39hf3d152e_0
  - unicodedata2=15.1.0=py39h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39h06a4308_0
  - wrapt=1.12.1=py39h3811e60_3
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=h5eee18b_1003
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=h5eee18b_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xorgproto=2024.1=h5eee18b_0
  - xorg-xproto=7.0.31=h5eee18b_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.43.0=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.4.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - attrs==25.1.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - datasets==3.3.2
      - dill==0.3.8
      - evaluate==0.4.3
      - executing==2.2.0
      - filelock==3.13.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - huggingface-hub==0.29.1
      - idna==3.10
      - ipdb==0.13.13
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - jinja2==3.1.4
      - jupyterlab-widgets==3.0.13
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.2.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - pillow==11.0.0
      - propcache==0.3.0
      - pyarrow==19.0.1
      - pytz==2025.1
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tokenizers==0.21.0
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - transformers==4.49.0
      - triton==3.2.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - widgetsnbextension==4.0.13
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: /homes/apartin/miniconda3/envs/cepi
